### ISSUE TITLE
Error taking screenshot: EOF

### ISSUE THREAD

**Issue by kenyee** [TarCV/uiautomatorviewer-gradle#38]
Has anyone ever seen this?

<img width="699" alt="Screenshot 2023-11-30 at 9 42 29 AM" src="https://github.com/TarCV/uiautomatorviewer-gradle/assets/586670/67cf3983-8983-49e3-8b43-6460d02c1f0d">

I pulled the latest but this still happens when I start up uiautomatorviewer via
./gradlew installDist
JAVA_OPTS=-XstartOnFirstThread ./build/install/uiautomatorviewer-gradle/bin/uiautomatorviewer-gradle

and then try getting a screenshot.

This is on an M1 mac if that matters.
Android Debug Bridge version 1.0.41
Version 34.0.5-10900879
Running on Darwin 23.1.0 (arm64)

java -version
openjdk version "17.0.7" 2023-04-18 LTS
OpenJDK Runtime Environment Zulu17.42+19-CA (build 17.0.7+7-LTS)
OpenJDK 64-Bit Server VM Zulu17.42+19-CA (build 17.0.7+7-LTS, mixed mode, sharing)

**Comment by TarCV** [comment]
I get similar issue if I try taking screenshots during an instrumented test run. Other possible reason is that the current activity blocks screenshots.
Are you able to take a screenshot with ADB? A command would be something like `adb shell screencap -p` or `adb exec-out screencap -p > screen.png` (the second variant might write error text into the file instead of an image in case of failure).

**Comment by kenyee** [comment]
and of course, now I try to repro and it doesn't have a problem 😞 

Closing issue.
Might want to put that suggestion in if you detect this error msg?  Otherwise, I'll try doing the adb shell screencap if I see this again.
