### ISSUE TITLE
Error : Build Failed with an Exception

### ISSUE THREAD

**Issue by Assia55** [TarCV/uiautomatorviewer-gradle#56]
![image](https://github.com/TarCV/uiautomatorviewer-gradle/assets/169766899/a6711130-6824-41de-9039-ea9ef5aa5357)

**Comment by TarCV** [comment]
This might be because Gradle didn't have full support for Java 22 at version 8.7. Now that Gradle 8.8 is released with full support of the latest Java I've updated this repository to use it.
Could you please retry with the latest commit? In case you get the same error please make sure you use the latest Gradle (8.8).

**Comment by TarCV** [comment]
Were you able to check with latest commits and recent version of Java?

**Comment by TarCV** [comment]
Closing for now. Feel free to re-open if you still get the error.
